name: Deploy AWS CDK

on:
  push:
    branches:
      - feature/gitactions
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install npm
        run: 'sudo apt-get update -y && sudo apt-get install nodejs npm -y'
        
      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Npm Install
        run: 'npm install'

      - name: CDK Synth
        run: 'cdk synth'

      - name: CDK Deploy
        run: 'cdk deploy'
